### ISSUE TITLE
Unity 5.6 Support need to be add ! ! ! 

### ISSUE THREAD

**Issue by WTF-Grinch** [yandexmobile/metrica-plugin-unity#11]
errors 

Assets/AppMetrica/Editor/PostprocessBuildPlayerAppMetrica.cs(4,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?

**Comment by bamx23** [comment]
I don't have such problem in Unity 5.6.1. Which build platform are you using which throw this exception on the building?
It looks like it wants `#if UNITY_IPHONE || UNITY_IOS` macros covering `PostprocessBuildPlayerAppMetrica.cs`

**Comment by WTF-Grinch** [comment]
some strange thing with Unity today its working
