### ISSUE TITLE
Не собирает на ios

### ISSUE THREAD

**Issue by dimmduh** [yandexmobile/metrica-plugin-unity#12]
` /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wdeprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -fno-objc-exceptions -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=7.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fembed-bitcode -iquote /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Pipes-generated-files.hmap -I/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Pipes-own-target-headers.hmap -I/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Pipes-all-target-headers.hmap -iquote /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Pipes-project-headers.hmap -I/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/include -I/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Classes -I/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios -I/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Classes/Native -I/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Libraries/bdwgc/include -I/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Libraries/libil2cpp/include -I/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/DerivedSources/armv7 -I/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/DerivedSources -F/Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -F/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Frameworks/Services/AppMetrica/Plugins/iOS -F/Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/UnityAds -DINIT_SCRIPTING_BACKEND=1 -fno-strict-overflow -DRUNTIME_IL2CPP=1 -include /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/PrecompiledHeaders/Prefix-dgvrfhwwuutvuegvfzyxnxzydcoy/Prefix.pch -MMD -MT dependencies -MF /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/YMMBridge.d --serialize-diagnostics /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/YMMBridge.dia -c /Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Libraries/Services/AppMetrica/Plugins/iOS/YMMBridge.m -o /Users/mac2/Library/Developer/Xcode/DerivedData/Unity-iPhone-alvmxycxzwlgxzfowryrxvtojmit/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/YMMBridge.o
[13:13:19]: ▸ /Users/mac2/builds/b12c593c/0/games/pipes/Build-ios/Libraries/Services/AppMetrica/Plugins/iOS/YMMBridge.m:3:9: fatal error: 'YandexMobileMetrica/YandexMobileMetrica.h' file not found
[13:13:19]: ▸ #import <YandexMobileMetrica/YandexMobileMetrica.h>
[13:13:19]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

fatal error: 'YandexMobileMetrica/YandexMobileMetrica.h' file not found

**Comment by bamx23** [comment]
Проверьте, что в Unity-проекте импортирован `YandexMobileMetrica.framework` и что в Xcode-проекте он также присутствует.

**Comment by dimmduh** [comment]
Да, пара файлов потерялась. Реимпорт помог. Спасибо.
