### ISSUE TITLE
Impossible to build iOS application with SDK 3.1.2 and 2.9.8

### ISSUE THREAD

**Issue by TursMA** [yandexmobile/metrica-plugin-unity#16]
Showing Recent Issues
ld: file is universal (5 slices) but does not contain a(n) arm64 slice: /Volumes/SSD2/xxxx_builds/build_01082018/Frameworks/Sources/Gizmo/third_party/AppMetrica/Plugins/iOS/YandexMobileMetrica.framework/YandexMobileMetrica file ‘/Volumes/SSD2/xxxx_builds/build_01082019/Frameworks/Sources/Gizmo/third_party/AppMetrica/Plugins/iOS/YandexMobileMetrica.framework/YandexMobileMetrica’ for architecture arm64

Switching to ARM64 architecture from Universal doesn't help.

**Comment by NesterovichAlexey** [comment]
Hi. 
What version of Unity? 
That prints command the `file YandexMobileMetrica` in `AppMetrica/Plugins/iOS/YandexMobileMetrica.framework`? 
Have you tried removing the plugin and re-import? 
Have you tried importing a plugin in a new project?

**Comment by TursMA** [comment]
Unity version: 2017.3.0f3

I've tried to rebuild with appmetrica another project and got the following:

`/Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Products/ReleaseForRunning-iphoneos/MyGame.app/MyGame normal arm64
    cd /Users/user/Desktop/fc
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH=“/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin”
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -L/Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Products/ReleaseForRunning-iphoneos -L/Users/user/Desktop/fc -L/Users/user/Desktop/fc/Libraries -L/Users/user/Desktop/fc/Libraries/SMTP/Plugins/iOS -F/Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Products/ReleaseForRunning-iphoneos -F/Users/user/Desktop/fc/Frameworks/Gizmo/third_party/AppMetrica/Plugins/iOS -filelist /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/MyGame.LinkFileList -Xlinker -map -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/MyGame-LinkMap-normal-arm64.txt -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/MyGame_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -ObjC -lz -lsqlite3 -lc++ -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -framework YandexMobileMetrica -lSKPSMTPSender -weak_framework Metal -framework CoreTelephony -framework AdSupport -framework Security -weak_framework SafariServices -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/MyGame_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/Unity-iPhone-auugnknfmflvbqfbkeonvzjhpszz/Build/Products/ReleaseForRunning-iphoneos/MyGame.app/MyGame

ld: file is universal (5 slices) but does not contain a(n) arm64 slice: /Users/user/Desktop/fc/Frameworks/Gizmo/third_party/AppMetrica/Plugins/iOS/YandexMobileMetrica.framework/YandexMobileMetrica file ‘/Users/user/Desktop/fc/Frameworks/Gizmo/third_party/AppMetrica/Plugins/iOS/YandexMobileMetrica.framework/YandexMobileMetrica’ for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by TursMA** [comment]
The issue was solved. YandexMobileMetrica file wasn't marked as binary file in git. Git tried to convert line-ending and brake it. I added the file into gitattributes as binary and now everything is ok. Sorry for disturbing.
