### ISSUE TITLE
Manifests conflicts

### ISSUE THREAD

**Issue by iderevitskiy** [yandexmobile/metrica-plugin-unity#22]
Install yandex-metric to Unity. At building to Android process I have an error.

"C:\Users\iderevitskiy\Documents\Party_Monster\Temp\gradleOut\src\main\AndroidManifest.xml:42:17-35 Error:
Attribute meta-data#metrica:api:level@value value=(72) from [:mobmetricalib-3.4.0:] AndroidManifest.xml:42:17-35
is also present at [:yandex-metrica] AndroidManifest.xml:27:17-35 value=(70).
Suggestion: add 'tools:replace="android:value"' to element at AndroidManifest.xml to override.
C:\Users\iderevitskiy\Documents\Party_Monster\Temp\gradleOut\src\main\AndroidManifest.xml:47:13-37 Error:
Attribute service#com.yandex.metrica.ConfigurationService@exported value=(false) from [:mobmetricalib-3.4.0:] AndroidManifest.xml:47:13-37
is also present at [:yandex-metrica] AndroidManifest.xml:32:13-36 value=(true).
Suggestion: add 'tools:replace="android:exported"' to element at AndroidManifest.xml:44:9-60:19 to override."

**Comment by NesterovichAlexey** [comment]
Hi.
You have two plugins with different versions of AppMetrica. You should find the .aar file with AppMetrica in another plugin and delete it. Most likely, it will be called yandex-metrica.aar and located in Assets/PLUGIN_NAME/Plugins/Android

**Comment by iderevitskiy** [comment]
Thank you, it's work!
