### ISSUE TITLE
How I can remove location permission for user's?

### ISSUE THREAD

**Issue by iderevitskiy** [yandexmobile/metrica-plugin-unity#23]
I don't need location tracking. But an app with AppMetrica asks users about it. Tips from page don't work. (https://appmetrica.yandex.ru/docs/mobile-sdk-dg/concepts/unity-plugin.html, about APP_METRICA_TRACK_LOCATION_DISABLED and off Location Tracking parameter in AppMetrica object)

**Comment by Trost123** [comment]
I have the same question.
Is there a way to avoid this? I don't need location data, all I need is install attributions.
Google warned me about this: https://i.imgur.com/Qx6rJ41.png

**Comment by NesterovichAlexey** [comment]
You can add following lines to AndroidManifest.xml:
```xml
<manifest xmlns:tools="http://schemas.android.com/tools" ...>
    <application>
        ...
        <service
            android:name="com.yandex.metrica.push.firebase.MetricaInstanceIdService"
            tools:node="remove" />
    </application>
</manifest>
```

**Comment by Trost123** [comment]
Ok, I added APP_METRICA_TRACK_LOCATION_DISABLED to "Scripting Define Symbols" (Unity project settings) and now there is no longer ACCESS_FINE_LOCATION in AndroidManifest.xml (so, problem solved I guess?)
But I wonder why disabling location tracing here in prefab doesn't remove that permission as well?
https://i.imgur.com/w6taJ2Z.png

**Comment by NesterovichAlexey** [comment]
AppMetrica Push Unity Plugin adds ```<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>``` in AndroidMainfest.xml
