### ISSUE TITLE
Appmetrica analytic work fine but tracker not count 

### ISSUE THREAD

**Issue by SajjadAlimohammadi** [yandexmobile/metrica-plugin-unity#28]
Hi
We use appmetrica analytic in our project, we implement the unity SDK.
Appmetrica analytic work fine , the tracker show clicks but not show any installation.
Any additional advice is welcome.
Thanks

**Comment by NesterovichAlexey** [comment]
In this case we need some more time and participation of our specialists. So, please, write us via form: https://appmetrica.yandex.com/docs/troubleshooting/other.html
Additionally, specify the app's APIKey and how you activate AppMetrica.

**Comment by SajjadAlimohammadi** [comment]
Dear @NesterovichAlexey thanks for your reply.
It was our issue in test tracker.
When you want to test attribution you have to test on a new device that the app never was not  installed.
So now the issue is solved.
