### ISSUE TITLE
Error Log for revenue!!!

### ISSUE THREAD

**Issue by CodeMasterYi** [yandexmobile/metrica-plugin-unity#31]
[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Revenue received for productID: <null> of quantity: <null> with price: null USD
we use PriceDecimal instead of Price...

**Comment by CodeMasterYi** [comment]
v3.6.0

**Comment by NesterovichAlexey** [comment]
Hi! Is it Android or iOS? What values do you transmit?

**Comment by CodeMasterYi** [comment]
I test it in Android.
And I use this constructor `public YandexAppMetricaRevenue(decimal priceDecimal, string currency)` to construct a revenue object.

**Comment by NesterovichAlexey** [comment]
Thank you for contacting us. We'll fix it.

**Comment by CodeMasterYi** [comment]
fix it, close it.
