### ISSUE TITLE
Updating unity plugin

### ISSUE THREAD

**Issue by dimmduh** [yandexmobile/metrica-plugin-unity#4]
Hi!
I see android plugin version is 2.60  (22-Nov-2016). And the last commit in this repo was 6 month ago. Can you update unity plugin?

**Comment by bamx23** [comment]
Hi @dimmduh 
We are planning to update the plugin soon(a week or two).
If you want to use the latest native Android SDK earlier you could update it by yourself:
1. [Download](http://repo1.maven.org/maven2/com/yandex/android/mobmetricalib/2.60/mobmetricalib-2.60-jar.jar) the library(jar).
2. Replace a jar from `Assets/Plugins/Android` with a new one.
3. Update API level in your `AndroidManifest.xml`: `<meta-data android:name="metrica:api:level" android:value="50"/>`

**Comment by dimmduh** [comment]
Thank you. If I will update this way, will new push notification service work?

**Comment by bamx23** [comment]
AppMetrica Push SDK will be provided by another Unity plugin. We're preparing it now. Both plugins will be released by the end of next week.

**Comment by bamx23** [comment]
Version 2.0.0 has been released. Feel free to close issue if everything works fine for you.
**AppMetrica Push Unity Plugin** is here: https://github.com/yandexmobile/metrica-push-plugin-unity/releases/latest
