### ISSUE TITLE
Skadnetwork support

### ISSUE THREAD

**Issue by bakwc** [yandexmobile/metrica-plugin-unity#43]
Hi! Do you support skadnetwork for ios14.5 and upper?

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 14799360. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp18.11.2021, 21:51, "Filipp Ozinov" ***@***.***>:
Hi! Do you support skadnetwork for ios14.5 and upper?
