### ISSUE TITLE
Не загружает приложение в appstore

### ISSUE THREAD

**Issue by n1kStas** [yandexmobile/metrica-plugin-unity#46]
Добрый день.
обновил сдк аппметрики под Unity до версии 4.1.0, приложение собирает под IOS, но при Upload выдает такое:
YandexMobileMetricaCrashes.framework/YandexMobileMetricaCrashes' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. 

YandexMobileMetrica.framework/YandexMobileMetrica' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. 

Причем, на этапе App Store Connect distribution options надо снимать галку с Upload your app's symbols, иначе ошибка с Symbols вылезет на этом шаге.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 15611392. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp21.01.2022, 07:55, "Stanislav" ***@***.***>:
Добрый день.
обновил сдк аппметрики под Unity до версии 4.1.0, приложение собирает под IOS, но при Upload выдает такое:
YandexMobileMetricaCrashes.framework/YandexMobileMetricaCrashes' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles.
YandexMobileMetrica.framework/YandexMobileMetrica' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles.
Причем, на этапе App Store Connect distribution options надо снимать галку с Upload your app's symbols, иначе ошибка с Symbols вылезет на этом шаге.

**Comment by DeMartery** [comment]
Такая же проблема.

**Comment by PaXLiCh** [comment]
Да, с обновлением проблема. Даже Ad-Hoc не собрать, при попытке экспортировать архив xcode пытается распарсить ipa и пишет IPA processing failed. В логах есть намёк на эту ошибку. А при заливке appstore версии такая же ошибка ITMS-90171.
Придётся откатывать.

**Comment by sshumihin** [comment]
тоже обновился и поймал ошибку при заливке в тф.

**Comment by dimmduh** [comment]
Та же проблема. Откатился.

**Comment by mopsicus** [comment]
Чтобы апп собирался надо удалить из Build Phases вот это
<img width="862" alt="Снимок экрана 2022-02-08 в 15 03 32" src="https://user-images.githubusercontent.com/17999592/152983452-24910f4c-593a-4e37-a9ef-24c169db4c9b.png">
