### ISSUE TITLE
iOS: ApplovinMediationYandexAdapter 4.4.2.1 doesn't completable with YandexMobileMetrica 4.0

### ISSUE THREAD

**Issue by DanMagor** [yandexmobile/metrica-plugin-unity#49]
![image](https://user-images.githubusercontent.com/17154257/158788897-54092fc6-9531-4234-92fa-5a1fb336f836.png)

For some reason, Xcode doesn't compile code with new Appmetrica adapter when you do not specify version in pod file:
![image](https://user-images.githubusercontent.com/17154257/158788456-63c3475c-b8e5-4cb1-92d4-4d8b9ab74f65.png)
Those new fields were added in AppMetrica 4.0 version.

But when you specify AppMetrica version in pod file: `pod 'YandexMobileMetrica', 4.0.0` it causes the problem that is described on the first screen: Adapter doesn't support version 4.0 or higher.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 16451008. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp17.03.2022, 13:22, "Anton Skudarnov" ***@***.***>:

For some reason, Xcode doesn't compile code with new Appmetrica adapter when you do not specify version in pod file:

Those new fields were added in AppMetrica 4.0 version.
But when you specify AppMetrica version in pod file: pod 'YandexMobileMetrica', 4.0.0 it cause the problem that is described on the first screen: Adapter doesn't support version 4.0 or higher.

**Comment by AppMetricaOvermindGenius180iq** [comment]
The solution is to put [version 3.8.0](https://github.com/yandexmobile/metrica-plugin-unity#version-380) of the Unity plugin and wait for the new version of Applovin, which will support Unity AppMetrica SDK 4+
