### ISSUE TITLE
Unity package contains previous version of plugin

### ISSUE THREAD

**Issue by Heathclliff** [yandexmobile/metrica-plugin-unity#60]
The current version of the [AppMetrica.unitypackage](https://github.com/yandexmobile/metrica-plugin-unity/blob/master/AppMetrica.unitypackage) file contains the contents of version 5.1.0, while the current version is 5.2.0.
You can also verify in the release commit (8c1194a3ed29f2b0501aa91d4a8137df9413da6d) that the file has not been updated.

**Comment by NudeNULL** [comment]
They forgot to include the new unity package into repository, but you can find it in releases page

**Comment by NesterovichAlexey** [comment]
Thank you for the signal. We have successfully corrected it.
