### ISSUE TITLE
Manifest not merged

### ISSUE THREAD

**Issue by dimmduh** [yandexmobile/metrica-plugin-unity#8]
I see in new version of appmetrica you moved Plugins directory to AppMetrica fodler.
I guess Unity required to place Manifest to Assets/Plugins/Android/
I use 5.4.0f3
that's why Unity does not merge manifest and Im getting error in log cat:
секция Развертывание
`Please check com.yandex.metrica.MetricaService in AndroidManifest file.
02-03 12:50:14.359 19251 19294 I Unity   : Attribute metrica:api:level should be equal to 52.
02-03 12:50:14.359 19251 19294 I Unity   :
02-03 12:50:14.359 19251 19294 I Unity   : com.yandex.metrica.impl.v$c:
02-03 12:50:14.359 19251 19294 I Unity   : Please check com.yandex.metrica.MetricaService in AndroidManifest file.
02-03 12:50:14.359 19251 19294 I Unity   : Attribute metrica:api:level should be equal to 52.
02-03 12:50:14.359 19251 19294 I Unity   :
02-03 12:50:14.359 19251 19294 I Unity   :      at com.yandex.metrica.impl.v.a(SourceFile:2107)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.yandex.metrica.impl.bk.b(SourceFile:4161)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.yandex.metrica.impl.bk.a(SourceFile:107)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.yandex.metrica.YandexMetrica.activate(SourceFile:58)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.unity3d.player.UnityPlayer.a(Unknown Source)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
02-03 12:50:14.359 19251 19294 I Unity   :      at android.os.Handler.dispatchMessage(Handler.java:98)
02-03 12:50:14.359 19251 19294 I Unity   :      at android.os.Looper.loop(Looper.java:158)
02-03 12:50:14.359 19251 19294 I Unity   :      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
02-03 12:50:14.359 19251 19294 I Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00085] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:25`

I moved your Plugins dir to Assets/ and it works fine

**Comment by bamx23** [comment]
As written in documentation you should modify your `Assets/Plugins/Android/AndroidManifest.xml` by yourself: https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/concepts/unity-plugin-docpage/#plugin-settings
We are planning to implement a "magic button" that will do it for you, but for now manual way is the only option.
Placing AppMetrica `AndroidManifest.xml` into `Assets/Plugins/Android` will lead to overwriting yours manifest on `.unitypackage` import what is not a good behaviour for plugin.

**Comment by dimmduh** [comment]
Thank you! I missed documentation update

**Comment by fessNiklas** [comment]
После обновления у меня та же проблема то в Android Studio. Ч в таком случае делать?
```
java.lang.RuntimeException: Unable to create application com.softjet.uralenergo.view.app.App: com.yandex.metrica.impl.w$c: 
    Please check com.yandex.metrica.MetricaService in AndroidManifest file.
    Attribute metrica:api:level should be equal to 61.
```
